### ISSUE TITLE
Can you give documentation for this?

### ISSUE THREAD

**Issue by sureshmariadass** [arisjulio/scorm-api-adapter#1]
I am new to SCORM. Can you explain how to use that?

**Comment by arisjulio** [comment]
As you will know, A [SCORM](https://scorm.com/scorm-explained/technical-scorm/scorm-12-overview-for-developers/) package is a set of web and media object to present information to an user.

To allow a SCORM Object to persist data you need an [adapter](https://scorm.com/scorm-explained/technical-scorm/scorm-12-overview-for-developers/#section-2) and a web service like a REST API.

This repo is a simple implementation of an adapter. You need to load the [minified file](https://github.com/arisjulio/scorm-api-adapter#download) in the parent window on which the SCORM will be loaded.

The SCORM calls the adapter when it needs to persists data and the adapter calls the web service. For [this implementation](https://github.com/arisjulio/scorm-api-adapter#installation) you need to specify a URL to commit the changes.

A sample POST request body to the endpoint looks like:
```JSON
{
  "question_1": "answer_1",
  "intereaction_2": "answer_2",
  "interaction_3": "B"
}
```

For this package, the endpoint must return a success field:
```JSON
{
  "success": true
}
```
